### ISSUE TITLE
bug: UnmarshalUnsafe panics when map values are empty strings

### ISSUE THREAD

**Issue by maheeshap-canopus** [planetscale/vtprotobuf#125]
I'm seeing an out of bounds panic when I try to use UnmarshalUnsafe on a message with a string->string map with empty values (e.g. 
`map[string]string{"testkey": ""}`):

I've added a test case to demonstrate this in https://github.com/planetscale/vtprotobuf/commit/0b13d368075de2ccbc1de711cf00e76ad8d1cda2 but I'm a bit unsure on what the cleanest solution is.

```
mahe:~/go/src/vtprotobuf/testproto/unsafe$ go test ./...
--- FAIL: Test_UnmarshalVTUnsafe (0.00s)
panic: runtime error: index out of range [44] with length 44 [recovered]
        panic: runtime error: index out of range [44] with length 44

goroutine 6 [running]:
testing.tRunner.func1.2({0x139fd60, 0xc00001a3d8})
        /Users/maheesha/go/go1.20.1/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
        /Users/maheesha/go/go1.20.1/src/testing/testing.go:1529 +0x39f
panic({0x139fd60, 0xc00001a3d8})
        /Users/maheesha/go/go1.20.1/src/runtime/panic.go:884 +0x213
github.com/planetscale/vtprotobuf/testproto/unsafe.(*UnsafeTest_Sub5).UnmarshalVTUnsafe(0xc0001098f0, {0xc00001c512, 0x2c, 0x2c})
        /Users/maheesha/go/src/vtprotobuf/testproto/unsafe/unsafe_vtproto.pb.go:3204 +0x934
github.com/planetscale/vtprotobuf/testproto/unsafe.(*UnsafeTest).UnmarshalVTUnsafe(0xc000137b58, {0xc00001c510, 0x2e, 0x2e})
        /Users/maheesha/go/src/vtprotobuf/testproto/unsafe/unsafe_vtproto.pb.go:3473 +0x79f
github.com/planetscale/vtprotobuf/testproto/unsafe.Test_UnmarshalVTUnsafe(0xc00016a000?)
        /Users/maheesha/go/src/vtprotobuf/testproto/unsafe/unsafe_test.go:193 +0x2115
testing.tRunner(0xc00016a000, 0x13f14b8)
        /Users/maheesha/go/go1.20.1/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /Users/maheesha/go/go1.20.1/src/testing/testing.go:1629 +0x3ea
FAIL    github.com/planetscale/vtprotobuf/testproto/unsafe      0.258s
FAIL
```

As far as I can tell, the panic occurs when a zero length string is the very last item to be unmarshalled. The offending generated line tries to touch dAtA[len(dAtA)]:
```
mapvalue = unsafe.String(&dAtA[iNdEx], intStringLenmapvalue) // vtprotobuf/testproto/unsafe/unsafe_vtproto.pb.go:3204
// len(dAtA) = 44,  iNdEx = 44, intStringLenmapvalue = 0 in my breaking test case
```
The safe unmarshalling equivalent uses subslicing which surprisingly is ok with the same type of indexing:
```
mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue]) // vtprotobuf/testproto/unsafe/unsafe_vtproto.pb.go:2249
// len(dAtA) = 44,  iNdEx = 44, postStringIndexmapvalue = 44 in my breaking test case
```

I was thinking of adding a naive check for zero length strings like:
```
if intStringLenmapvalue != 0 {
    mapvalue = unsafe.String(&dAtA[iNdEx], intStringLenmapvalue)
}
```
but this isn't compatible with the existing unsafe_test.go which checks that mapvalue is backed by the original data.

Wanted to raise an issue to see if anyone else has any ideas on how fix this without modifying the test logic too much/introducing other side effects.
Thanks!

**Comment by nockty** [comment]
Interesting edge case, thank you for reporting this bug very clearly! For now I have a couple quick thoughts:
- when `intStringLenmapvalue` is `0`, we could use `nil` instead of `&dAtA[iNdEx]`: `unsafe.String(nil, 0)` should do the job AFAIK.
- in this case, the value is not backed by the original data, which makes sense. I think it's OK to not perform this check for empty strings in the test cases because it doesn't make sense for them anyway. Maybe it would work to compare it against the `nil` pointer, though. Here is what I have in mind:

```diff
func assertStringIsOriginal(t *testing.T, s string, belongs bool, originalData []byte) {
+	start := uintptr(unsafe.Pointer(unsafe.StringData(s)))
+	// empty string has no underlying array, compare pointer to nil
+	if len(s) == 0 {
+		assert.Equal(t, uintptr(unsafe.Pointer(nil)), start)
+		return
+	}
+	end := start + uintptr(len(s)) - 1
+
	originalStart := uintptr(unsafe.Pointer(unsafe.SliceData(originalData)))
	originalEnd := originalStart + uintptr(len(originalData)) - 1

-	start := uintptr(unsafe.Pointer(unsafe.StringData(s)))
-	end := start + uintptr(len(s)) - 1
	assert.Equal(t, belongs, start >= originalStart && start < originalEnd)
	assert.Equal(t, belongs, end > originalStart && end <= originalEnd)
}
```

What do you think about this?

**Comment by maheeshap-canopus** [comment]
@nockty Thanks, that fix looks good to me.

I also noticed this panic occurs with empty strings in oneof fields:
```
--- FAIL: Test_UnmarshalVTUnsafe (0.00s)
panic: runtime error: index out of range [2] with length 2 [recovered]
        panic: runtime error: index out of range [2] with length 2

goroutine 18 [running]:
testing.tRunner.func1.2({0x139fea0, 0xc0000b0318})
        /Users/maheesha/go/go1.20.1/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
        /Users/maheesha/go/go1.20.1/src/testing/testing.go:1529 +0x39f
panic({0x139fea0, 0xc0000b0318})
        /Users/maheesha/go/go1.20.1/src/runtime/panic.go:884 +0x213
github.com/planetscale/vtprotobuf/testproto/unsafe.(*UnsafeTest_Sub4).UnmarshalVTUnsafe(0xc0000a2f00, {0xc0000a4842, 0x2, 0x2})
        /Users/maheesha/go/src/vtprotobuf/testproto/unsafe/unsafe_vtproto.pb.go:3015 +0x835
github.com/planetscale/vtprotobuf/testproto/unsafe.(*UnsafeTest).UnmarshalVTUnsafe(0xc0000dbca8, {0xc0000a4840, 0x4, 0x4})
        /Users/maheesha/go/src/vtprotobuf/testproto/unsafe/unsafe_vtproto.pb.go:3444 +0xa34
github.com/planetscale/vtprotobuf/testproto/unsafe.Test_UnmarshalVTUnsafe(0xc000082ea0?)
        /Users/maheesha/go/src/vtprotobuf/testproto/unsafe/unsafe_test.go:153 +0x1811
testing.tRunner(0xc000082ea0, 0x13f15f8)
        /Users/maheesha/go/go1.20.1/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /Users/maheesha/go/go1.20.1/src/testing/testing.go:1629 +0x3ea
```

I've used the same approach to fix this, will raise a PR now.
